//DADOS INICIAIS DO JOGO



//EVENTOS DE CLIQUES QUE TERÁ NO JOGO





/* 
    FUNÇÕES PARA FAZER O JOGO ACONTECER

1 - FUNÇÃO PARA RESETAR O JOGO 

2 - FUNÇÃO PARA RENDERIZAR O JOGO

3 - FUNÇÃO PARA RENDERIZAR INFORMAÇÕES DO JOGO

4 - FUNÇÃO PARA ITEM CLICADO (FAZER VERIFICAÇÃO PRA SABER SE ESTÁ VAZIO O ESPAÇO CLICADO)

5 - FUNÇÃO PARA TROCAR O JOGADOR CADA JOGADA


*/